- src/App.js
- src/styles/GlobalStyle.js
- src/styles/theme.js
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [set/#4] 공통 스타일 추가 및 App.js 스타일 선언 완료

- src/styles/theme.js
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [feat/#10] 공통 스타일 이미지 추가

- src/components/button.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [FEAT] button

- src/components/DownloadButton.jsx
- src/components/ExButton.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [FEAT] Download, Ex Button

- src/components/DownloadButton.jsx
- src/components/ExButton.jsx
- src/components/SampleButton.jsx
- src/components/SolveButton.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- DownloadButton, ExButton, SampleButton, SolveButton.jsx 내 선언된 버튼 컴포넌트 명 수정
- export default 값 컴포넌트 명과 동일하게 수정
- GlobalStyle 속성 제거
<br>
-
<br>
<br>
> [DESIGN] 버튼 컴포넌트명 및 export 수정

- package.json
- src/App.js
- src/components/ExButton.jsx
- src/pages/UserPage.jsx
마이페이지 중 요약페이지 완료 
- 파일명과 날짜를 파일 박스 안으로 넣어봤습니당
- 글씨 색은 하늘색으로 해놓았는데, 검은색으로 했을 때와 비교해서 말해주세요☺️
현재 파일
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [DESIGN] MyPage - summary

- package-lock.json
- package.json
- src/App.js
- src/components/ExButton.jsx
- src/pages/SamplePage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [DESIGN] SamplePage - 요약본 생성 페이지

- src/App.js
- src/pages/UploadPage.jsx
- src/pages/UserPageSample.jsx
<br>
footer.jsx 파일 수정 이전이라 footer 안보임
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [Design] 강의자료 업로드 페이지 (UploadPage)

- package.json
- src/components/LoginBox.jsx
- src/components/LoginInputForm.jsx
- src/components/LoginToggle.jsx
- src/pages/LoginPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 디자인 수정
<로그인/회원가입 기본 화면>
<입력창 포커스/버튼 활성화>
<br>
-
<br>
<br>
> [DESIGN] 로그인/회원가입 페이지 (LoginPage) 디자인 수정

- src/components/SampleButton.jsx
- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 작업 버튼 경로 수정
- 디자인 디테일 수정
- SampleButton 옵션 수정
<기본 화면>
<자료 업로드>
<업로드 버튼 클릭 시 모달창 출력>
<업로드 완료 시 작업 버튼 모달 출력>
<br>
-
<br>
<br>
> [DESIGN] 업로드 페이지 디자인 수정

- src/pages/AdditionalCompletePage.jsx
- src/pages/CheckCompletePage.jsx
- src/pages/PracticeCompletePage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 각 버튼에 라우터 적용
<br>
-
<br>
<br>
> [FEAT] 채점/문제생성/추가문제생성 완료 페이지 (CheckCompletePage, PracticeCompletePage, AdditionalCompletePage) 기능구현

- package-lock.json
- src/axiosInstance.js
- src/components/LoginInputForm.jsx
- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [Feat] 학습자료 업로드/요약본 api  연동

- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> feat) 강의자료 업로드 페이지 디자인 수정

- axiosInstance.js
- src/components/Introduce.jsx
- src/components/ScrollIndicator.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [Feat] 마이페이지 로그인 시 라우팅

- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
- src/pages/UserPageSample.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [feat] 요약본 마이페이지에 연결하기

- src/pages/CreatePracPage.jsx
- src/pages/PracticeCompletePage.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/PracticePage/ProblemList.jsx
- src/pages/PracticePage/Subjective.jsx
- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 연습문제 생성 API 연동
- API 응답 값 <-> 연습문제 풀이 페이지 연결
<br>
-
<br>
<br>
> [FEAT] 연습문제 생성 API 연동 / 연습 문제 풀이 페이지 기능 구현

- src/pages/SamplePage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [FEAT]  샘플 페이지 디자인 오류 수정

- src/pages/CreatePracPage.jsx
- src/pages/PracticeCompletePage.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/PracticePage/ProblemList.jsx
- src/pages/PracticePage/Subjective.jsx
- src/pages/UserPageEx.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 연습 문제 생성 API 생성본 마이페이지 연동 완료
- 연습 문제 삭제 API 연동 완료
- 연습 문제 조회 API 연동 완료
<br>
-
<br>
<br>
> [FEAT] 연습 문제 생성본 - 마이페이지 연결

- src/pages/GradingResults.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/PracticePage/ProblemList.jsx
- src/pages/PracticePage/Subjective.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 채점 API 연동 완료
- 스타일 관련 수정 필요 (추가 이슈로 작업 예정)
- Subjective 옵션 수정 필요 (추가 이슈로 작업 예정) 
<br>
-
<br>
<br>
> [FEAT] 채점 API 연동

- src/pages/GradingResults.jsx
- src/pages/NotePage/WrongAnswer.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/ProblemContent.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [Feat] 오답 조회 api 연동 

- src/pages/GradingResults.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/Subjective.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 채점 API 수행 후 결과화면에서 오답, 정답 구분 색상 반영
<br>
-
<br>
<br>
> [DESIGN] 채점 기능 수행 후 문제에 적용되는 스타일 수정

- src/pages/CreatePracPage.jsx
- src/pages/GradingResults.jsx
- src/pages/NotePage/WrongAnswer.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
- src/pages/UserPageNote.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 오답노트 생성본 마이페이지에 자동 저장 기능 구현
- 오답노트 저장 시 이름(토픽_오답노트), 생성 날짜 자동 저장 및 마이페이지 컨텐츠 카드에 출력
<마이페이지 - 오답노트>
<br>
-
<br>
<br>
> [FEAT] 오답노트 생성본 마이페이지에 연결

- src/pages/CreatePracPage.jsx
- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 문제 유형 자료 파인콘 업로드 API 연동
- 파일 업로드 클릭 시 API 호출할 수 있는 모달창 구성
<모달창 - 다음 클릭 시 파인콘 업로드 API 호출>
<br>
-
<br>
<br>
> [FEAT] 문제 생성 페이지 파인콘 업로드 API 연동 및 모달창 구현

- src/pages/MorePracticePage/MoreMultipleChoice.jsx
- src/pages/MorePracticePage/MoreSubjective.jsx
- src/pages/PracticePage/MultipleChoice.jsx
- src/pages/PracticePage/Subjective.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 연습 문제 / 추가 연습 문제 채점 후 결과 페이지에 답안이 같이 출력되는 기능 구현
<객관식>
<주관식>
<br>
-
<br>
<br>
> [FEAT] 채점 페이지 답안 출력 기능 구현

- src/pages/CreatePracPage.jsx
- src/pages/MorePracticePage/MoreProblemContent.jsx
- src/pages/NotePage/WrongAnswer.jsx
- src/pages/PracticeCompletePage.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/SamplePage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 각종 로딩 모달 구현
- 
<샘플페이지 요약본 불러오기 로딩 스피너>
<연습 문제 생성 / 추가 연습 문제 생성>
<채점하기>
<br>
-
<br>
<br>
> [DESIGN] 연습 문제, 추가 연습 문제 생성 / 채점 / 요약본 불러오기 로딩 모달 구현

- src/components/LoginInputForm.jsx
- src/pages/AdditionalCompletePage.jsx
- src/pages/CreatePracPage.jsx
- src/pages/MorePracticePage/MoreProblemContent.jsx
- src/pages/MorePracticePage/MoreWrongAnswer.jsx
- src/pages/NotePage/WrongAnswer.jsx
- src/pages/PracticeCompletePage.jsx
- src/pages/PracticePage/ProblemContent.jsx
- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
- src/pages/UserPageEx.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- API 엔드포인트 끝부분 / 제거
- 파인콘 업로드 API 경로 변경으로 인해 수정
<br>
-
<br>
<br>
> [FIX] 전체 API 엔드포인트 수정 및 파인콘 업로드 API 엔드포인트 경로 수정

- Jenkinsfile
- package-lock.json
- package.json
- src/reportWebVitals.js
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [Feat/#104] 젠킨스파일 집어넣기

- src/pages/AdditionalCompletePage.jsx
- src/pages/CreatePracPage.jsx
- src/pages/MorePracticePage/MoreWrongAnswer.jsx
- src/pages/NotePage/WrongAnswer.jsx
- src/pages/PracticeCompletePage.jsx
- src/pages/PracticePage/Subjective.jsx
- src/pages/SamplePage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- CreatePracPage 업로드 영역 문구 수정, 비율 조정, 구분선 길이 조정
- GradingResults 주관식 부분 정답이 길어져도 일정한 양식을 유지할 수 있게 수정
- 마이페이지로 이동하는 버튼에 파인콘 데이터 삭제 API 연동
<연습 문제 생성 페이지>
<채점 결과 페이지>
<br>
-
<br>
<br>
> [DESIGN] 디자인 디테일 수정 (CreatePracPage, GradingResults) 및 파인콘 데이터 삭제 API 연동

- src/pages/MorePracticePage/MoreMultipleChoice.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [FEAT] 헷갈리는 문제 너 아웃!

- src/pages/MorePracticePage/MoreWrongAnswer.jsx
- src/pages/SamplePage.jsx
- src/pages/UploadPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 
<br>
-
<br>
<br>
> [FEAT] 디자인 수정사항 등등

- src/pages/CreatePracPage.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 문제 유형 업로드 API 교체 (pdf/upload -> pdf/genealogy-upload) 
<br>
-
<br>
<br>
> [FIX] 문제 유형 업로드 API 교체

- src/pages/MorePracticePage/MoreWrongAnswer.jsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- 일반 오답 노트 페이지와 디자인 통일
<br>
-
<br>
<br>
> [DESIGN] 추가 오답노트 페이지 디자인 수정
